### PR TITLE
GRAL-4241 vulnerabilities fix

### PR DESCRIPTION
**Pull request by dmitriyeff**
app-extensions-sdk high vulnerabilities fix

Installed this branch [here](https://github.com/pipedrive/marketplace-app-extensions-ui/compare/master...GRAL-4241)

- Checkout [marketplace app extensions](https://github.com/pipedrive/marketplace-app-extensions-ui/compare/master...GRAL-4241)
- Run `rm -rf node_modules && rm -rf build-detached`
- Run `npm i`
- Run cypress tests: `npm run test:functional:cypress:run` (All tests should pass)

Check for vulnerabilities in the package:
- Run `npm audit` against app-extenstions-sdk and see if there are no vulnerabilities

### CODE REVIEW

**Review by Reivilo85k — DISMISSED** [review]
Works on my machine

**Review by Reivilo85k — DISMISSED** [review]

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ⚠


<details><summary><strong> ⚠ Use of actively maintained version of Node.js</strong></summary>
<br/>

**Message:** A service using Node.js should use an actively maintained version before it reaches EOL.

<table>
<thead>
	<tr>
			<th>Current Node.js version</th>
			<th>Message</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><code>16</code></td>
				<td>The current version of Node.js has already reached its EOL (2023-09-11)</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/checkNextNodeRelease)
<br/>
</details>

<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/app-extensions-sdk/tree/be56d5cffd99bc64a849a3be75e725e48353b376/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>lint</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora, eks-runner-neodora-bulk, eks-runner-secops]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/app-extensions-sdk/tree/be56d5cffd99bc64a849a3be75e725e48353b376/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>lint</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Unknown tribe name</strong></summary>
<br/>

**Message:** The property `owner` in `repository.json` must be a valid tribe name present in **mission-tracking**
**Repository file:** [repository.json](https://github.com/pipedrive/app-extensions-sdk/tree/be56d5cffd99bc64a849a3be75e725e48353b376/repository.json)

<table>
<thead>
	<tr>
			<th>Owner status</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td>'GRAVITY' is an unknown tribe name</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/tribeName)
<br/>
</details>


Commit [`be56d5c`](https://github.com/pipedrive/app-extensions-sdk/commit/be56d5cffd99bc64a849a3be75e725e48353b376/)  Job [`379411`](https://jenkins.pipedrive.tools/job/neodora/379411/)

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ⚠


<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/app-extensions-sdk/tree/be56d5cffd99bc64a849a3be75e725e48353b376/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>lint</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora, eks-runner-neodora-bulk, eks-runner-secops]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/app-extensions-sdk/tree/be56d5cffd99bc64a849a3be75e725e48353b376/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>lint</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Use of actively maintained version of Node.js</strong></summary>
<br/>

**Message:** A service using Node.js should use an actively maintained version before it reaches EOL.

<table>
<thead>
	<tr>
			<th>Current Node.js version</th>
			<th>Message</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><code>16</code></td>
				<td>The current version of Node.js has already reached its EOL (2023-09-11)</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/checkNextNodeRelease)
<br/>
</details>

<details><summary><strong> ⚠ Unknown tribe name</strong></summary>
<br/>

**Message:** The property `owner` in `repository.json` must be a valid tribe name present in **mission-tracking**
**Repository file:** [repository.json](https://github.com/pipedrive/app-extensions-sdk/tree/be56d5cffd99bc64a849a3be75e725e48353b376/repository.json)

<table>
<thead>
	<tr>
			<th>Owner status</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td>'GRAVITY' is an unknown tribe name</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/tribeName)
<br/>
</details>


Commit [`be56d5c`](https://github.com/pipedrive/app-extensions-sdk/commit/be56d5cffd99bc64a849a3be75e725e48353b376/)  Job [`379448`](https://jenkins.pipedrive.tools/job/neodora/379448/)

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ⚠


<details><summary><strong> ⚠ Use of actively maintained version of Node.js</strong></summary>
<br/>

**Message:** A service using Node.js should use an actively maintained version before it reaches EOL.

<table>
<thead>
	<tr>
			<th>Current Node.js version</th>
			<th>Message</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><code>16</code></td>
				<td>The current version of Node.js has already reached its EOL (2023-09-11)</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/checkNextNodeRelease)
<br/>
</details>

<details><summary><strong> ⚠ Incorrect runner in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow must run on a self-hosted runner

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Actual runs-on value</th>
			<th>Expected runs-on value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/app-extensions-sdk/tree/2134a021f906a05e08c9690245c152eac2194d27/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>lint</code></td>
				<td><code>ubuntu-latest</code></td>
				<td><code>Any of [eks-runner, eks-runner-php, eks-runner-nano, eks-runner-debug, eks-runner-compute, eks-runner-cd, eks-runner-ci, eks-runner-neodora, eks-runner-neodora-bulk, eks-runner-secops]</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowRunner)
<br/>
</details>

<details><summary><strong> ⚠ Missing cache in Github Workflow</strong></summary>
<br/>

**Message:** Github workflow should be using caching when step uses `actions/setup-node`

<table>
<thead>
	<tr>
			<th>Workflow file</th>
			<th>Job name</th>
			<th>Step index</th>
			<th>Actual cache value</th>
			<th>Expected cache value</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><a href="https://github.com/pipedrive/app-extensions-sdk/tree/2134a021f906a05e08c9690245c152eac2194d27/.github/workflows/on-commit.yml">on-commit.yml</a></td>
				<td><code>lint</code></td>
				<td>2</td>
				<td><code>Not found</code></td>
				<td><code>npm</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/workflowCache)
<br/>
</details>

<details><summary><strong> ⚠ Unknown tribe name</strong></summary>
<br/>

**Message:** The property `owner` in `repository.json` must be a valid tribe name present in **mission-tracking**
**Repository file:** [repository.json](https://github.com/pipedrive/app-extensions-sdk/tree/2134a021f906a05e08c9690245c152eac2194d27/repository.json)

<table>
<thead>
	<tr>
			<th>Owner status</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td>'GRAVITY' is an unknown tribe name</td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/tribeName)
<br/>
</details>


Commit [`2134a02`](https://github.com/pipedrive/app-extensions-sdk/commit/2134a021f906a05e08c9690245c152eac2194d27/)  Job [`379543`](https://jenkins.pipedrive.tools/job/neodora/379543/)

**Pull request merged**
